# Generated by Django 5.0.14 on 2026-08-20 21:08

import django.core.validators
import expenses.models
import expenses.pdf_analysis
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expensereport_supervisor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldocument',
            name='file',
            field=models.FileField(upload_to=expenses.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), expenses.models.validate_file_size, expenses.pdf_analysis.validate_pdf_page_count], verbose_name='File'),
        ),
    ]
