# Generated by Django 5.0.14 on 2026-08-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_approvedexpensereport_expensereport_excel_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldocument',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('MXN', 'MXN')], default='USD', max_length=3, verbose_name='Currency'),
        ),
    ]
