# Generated by Django 5.0.14 on 2026-08-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_traveldocument_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldocument',
            name='backup_type',
            field=models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('no_invoice', 'No invoice')], default='invoice', max_length=20, verbose_name='Backup'),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vendor legal name'),
        ),
    ]
