# Generated by Django 5.0.14 on 2026-08-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
