# Generated by Django 5.0.14 on 2026-08-20 17:57

import django.core.validators
import django.db.models.deletion
import expenses.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_traveldocument_original_filename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='approval_clause',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='ceo_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='amount_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='detected_type',
            field=models.CharField(blank=True, choices=[('taxi', 'Taxi'), ('meal', 'Meal'), ('flight', 'Flight'), ('hotel', 'Hotel'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='extracted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='type_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='review_note',
            field=models.TextField(blank=True, verbose_name='Review note'),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='document_date',
            field=models.DateField(verbose_name='Expense date'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='file',
            field=models.FileField(upload_to=expenses.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), expenses.models.validate_file_size], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='type',
            field=models.CharField(choices=[('taxi', 'Taxi'), ('meal', 'Meal'), ('flight', 'Flight'), ('hotel', 'Hotel'), ('other', 'Other')], max_length=20, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='ExpenseReportAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('document_uploaded', 'Document uploaded'), ('document_deleted', 'Document deleted'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=30)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='expenses.expensereport')),
            ],
            options={
                'verbose_name': 'Audit log entry',
                'verbose_name_plural': 'Audit log entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
