# Generated by Django 5.0.14 on 2026-08-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remap_legacy_doctype_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='supervisor_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Supervisor email'),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='supervisor_name',
            field=models.CharField(default='', max_length=150, verbose_name='Supervisor name'),
        ),
    ]
