# Generated by Django 5.0.14 on 2026-08-20 21:57

import django.core.validators
import expenses.models
import expenses.pdf_analysis
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_traveldocument_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedExpenseReport',
            fields=[
            ],
            options={
                'verbose_name': 'Approved report (history)',
                'verbose_name_plural': 'Approved reports (history)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('expenses.expensereport',),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='excel_snapshot',
            field=models.FileField(blank=True, upload_to='reports/%Y/%m'),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='word_snapshot',
            field=models.FileField(blank=True, upload_to='reports/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='file',
            field=models.FileField(blank=True, upload_to=expenses.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), expenses.models.validate_file_size, expenses.pdf_analysis.validate_pdf_page_count], verbose_name='File'),
        ),
    ]
