schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}

type Note @aws_cognito_user_pools @aws_iam {
  id: ID!
  owner: String!
  title: String!
  content: String
  createdAt: AWSDateTime!
}

input CreateNoteInput {
  title: String!
  content: String
}

type NoteConnection @aws_cognito_user_pools {
  items: [Note]
  nextToken: String
}

type Query {
  getNote(id: ID!): Note @aws_cognito_user_pools
  listNotes(limit: Int, nextToken: String): NoteConnection @aws_cognito_user_pools
}

type Mutation {
  createNote(input: CreateNoteInput!): Note @aws_cognito_user_pools
  deleteNote(id: ID!): Note @aws_cognito_user_pools
}

type Subscription {
  # Tiempo real vía WebSockets administrados por AppSync
  onCreateNote: Note @aws_subscribe(mutations: ["createNote"]) @aws_cognito_user_pools
}
