# Generated by Django 5.0.14 on 2026-08-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_department_loginevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Employee number'),
        ),
    ]
