# Generated by Django 5.0.14 on 2026-08-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_backfill_employee_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervised_department',
            field=models.CharField(blank=True, help_text='For a department admin: the one department whose submitted reports they can see and approve. Leave blank for regular employees and for the general/HR admin (who sees every department via is_superuser).', max_length=100, verbose_name='Supervises department (admin only)'),
        ),
    ]
